### PR TITLE
remove AbbreviatedTypes usage

### PR DESCRIPTION
**Pull request by stevengj**
@wsshin, I'm not really a fan of using AbbreviatedTypes here — I think it makes the code much harder to read for anyone who isn't you, since most of the Julia community does not use these abbreviations. 

This PR shouldn't affect any of your code using GeometryPrimitives, since the API is the same — the types are not changed, just spelled differently internally.

Closes #40.

### CODE REVIEW

**Comment by wsshin** [comment]
Agreed.  I think I went too far with type aliases.  Maybe I should remove the usage of `AbbreviatedTypes` from my other packages all together.

**Comment by wsshin** [comment]
In my other package, I have a function argument typed
```julia
Tuple2{NTuple{K,AbsVecReal}} where {K}
```
, which would be typed  
```julia
NTuple{2,NTuple{K,AbstractVector{<:Real}}} where {K}
```
or
```julia
Tuple{NTuple{K,AbstractVector{<:Real}},NTuple{K,AbstractVector{<:Real}}} where {K}
```
without type aliasing.  I feel that these are too long and hard to read.  Do you think type aliasing is still bad in this case?

**Comment by stevengj** [comment]
Maybe you should re-think your function and/or data types if the signature needs to be that complicated…

**Comment by wsshin** [comment]
The function is here: https://github.com/wsshin/StaggeredGridCalculus.jl/blob/8b27e26d5ffea0b530bf69f53591753e09024bd1/src/pml.jl#L91-L100

The arguments typed `Tuple2{NTuple{K,AbsVecReal}} where {K}` are `l` and `∆l` (the finite-difference grid point locations and the separations between them).  `K` is the dimension of the space being discretized.   The reason for `Tuple2` is to pass the primal and dual grids.
 
As shown in the above link, I do have a wrapper function taking a struct `Grid` that contains `l` and `∆l`, but I prefer having a function that takes `l` and `∆l` directly, because not all the fields of `Grid` are needed by the function.  This allows me to use the function without constructing a `Grid`.

**Pull request merged**
