### PR TITLE
Add vxlcut.jl for volume fraction of voxel cut by plane

### PR DESCRIPTION
**Pull request by wsshin**
This PR adds capability to calculate the volume fraction of the sub-volume of a voxel cut by a plane.  (The main function is `volfrac` in `src/vxlcut.jl`.)

The PR also adds detailed unit tests.

### CODE REVIEW

**Comment by stevengj** [comment]
Needs a rebase after #7, which should hopefully fix the test failures?

**Comment by wsshin** [comment]
Hmmm...  Rebase is done, but the test still fail.  Not sure why.  On my local repository unit tests succeed on both Julia 0.6 and 0.7.

The details of the the test show that it succeeded on Julia 0.6, but failed on the nightly build.  Does this nightly build mean the up-to-date 0.7?  I will pull the Julia master branch, rebuild Julia, and do the test again.

Any suggestions?

**Comment by stevengj** [comment]
Nightly is an up-to-date (less than 24 hours old, I think) 0.7.

**Comment by wsshin** [comment]
Did test on the nightly build, and the test fails at `@test @inferred(hash(s)) == hash(deepcopy(s))` where `s` is a `Shape` instance.  For some reason, our custom `hash(s)` is type-unstable on the nightly build.

MWE.  Consider the following custom type:
```julia
julia> VERSION
v"0.7.0-DEV.881"

julia> struct MyTypeVec
           x::Vector{Int}
       end
```
`hash` on an instance of `MyTypeVec` is stable:
```julia
julia> m = MyTypeVec([3.,4.])
MyTypeVec([3, 4])

julia> @code_warntype hash(m)
Variables:
  #self#::Base.#hash
  x::MyTypeVec

Body:
  begin
      $(Expr(:inbounds, false))
      # meta: location number.jl zero 204
      # meta: location int.jl convert 463
      # meta: location int.jl check_top_bit 404
      unless ((Base.lshr_int)(0, (Base.sub_int)((Base.shl_int)(8, 0x03)::Int64, 1)::Int64)::Int64 === (Base.zext_int)(Int64, 0x01)::Int64)::Bool goto 7
      (Base.throw)($(QuoteNode(InexactError())))::Union{}
      7:
      # meta: pop location
      # meta: pop location
      # meta: pop location
      $(Expr(:inbounds, :pop))
      return $(Expr(:invoke, MethodInstance for hash(::Any, ::UInt64), :(Base.hash), :(x), :((Base.bitcast)(UInt64, 0))))::UInt64
  end::UInt64
```
However, as soon as we define a custom `hash`, it becomes unstable:
```julia
julia> Base.hash(m::MyTypeVec, h::UInt) = hash(m.x, hash(:MyTypeVec, h))

julia> @code_warntype hash(m)
Variables:
  #self#::Base.#hash
  x::MyTypeVec

Body:
  begin
      $(Expr(:inbounds, false))
      # meta: location number.jl zero 204
      # meta: location int.jl convert 463
      # meta: location int.jl check_top_bit 404
      unless ((Base.lshr_int)(0, (Base.sub_int)((Base.shl_int)(8, 0x03)::Int64, 1)::Int64)::Int64 === (Base.zext_int)(Int64, 0x01)::Int64)::Bool goto 7
      (Base.throw)($(QuoteNode(InexactError())))::Union{}
      7:
      # meta: pop location
      # meta: pop location
      # meta: pop location
      $(Expr(:inbounds, :pop))
      return $(Expr(:invoke, MethodInstance for hash(::Array{Int64,1}, ::UInt64), :(Main.hash), :((Core.getfield)(x, :x)::Array{Int64,1}), :($(Expr(:invoke, MethodInstance for hash(::Any, ::UInt64), :(Main.hash), :(:MyTypeVec), :((Base.bitcast)(UInt64, 0))))::UInt64)))::Any
  end::Any
```

The instability seems to occur when the custom type has an array field.  If the custom type has only a scalar field, such a custom `hash` remains stable:
```julia
julia> struct MyTypeInt
           x::Int
       end

julia> Base.hash(m::MyTypeInt, h::UInt) = hash(m.x, hash(:MyTypeInt, h))

julia> m = MyTypeInt(0)
MyTypeInt(0)

julia> @code_warntype hash(m)
Variables:
  #self#::Base.#hash
  x::MyTypeInt

Body:
  begin
      $(Expr(:inbounds, false))
      # meta: location number.jl zero 204
      # meta: location int.jl convert 463
      # meta: location int.jl check_top_bit 404
      unless ((Base.lshr_int)(0, (Base.sub_int)((Base.shl_int)(8, 0x03)::Int64, 1)::Int64)::Int64 === (Base.zext_int)(Int64, 0x01)::Int64)::Bool goto 7
      (Base.throw)($(QuoteNode(InexactError())))::Union{}
      7:
      # meta: pop location
      # meta: pop location
      # meta: pop location
      $(Expr(:inbounds, :pop))
      return $(Expr(:invoke, MethodInstance for hash(::MyTypeInt, ::UInt64), :(Base.hash), :(x), :((Base.bitcast)(UInt64, 0))))::UInt64
  end::UInt64
```

Should I file an issue on this to `JuliaLang/julia`?

**Comment by stevengj** [comment]
Looks like a bug in 0.7; I filed an issue.  For now, I would removed the `@inferred` check.

**Comment by wsshin** [comment]
Thanks for the confirmation and filing an issue!  I agree with removing `@inferred` from the tests on `hash` and have made changes accordingly.

**Comment by wsshin** [comment]
Made some further charges:
- Use the term "corner" consistently instead of "vertex".
- Use `corner(vxl, s[X], s[Y], s[Z])` instead of `corner(vxl, s...)` to eliminate allocations associated with splat (14 allocations → 0).  Now all `volfrac` calls use zero allocations.  

I don't have anything to change at this point.  If it looks good to you, please feel free to merge.

**Pull request merged**
